export enum ModuleCode {
  // Core modules - using PascalCase to match backend permission codes
  Dashboard = 'Dashboard',
  Vendor = 'Vendor',
  Material = 'Material',
  PurchaseOrder = 'PurchaseOrder',
  GRN = 'GRN',
  GRNFieldConfig = 'GRNFieldConfig',
  QC = 'QC',
  GatePass = 'GatePass',
  Report = 'Report',
  User = 'User',
  Role = 'Role',
  Setting = 'Setting',
  Tenant = 'Tenant',
  Plan = 'Plan',
  Subscription = 'Subscription',
  Upload = 'Upload',
  SuperAdmin = 'SuperAdmin',
  Notification = 'Notification',
  ExternalDbConfig = 'ExternalDbConfig',
  RFID = 'RFID',
}

export const ModuleDefinitions: Record<ModuleCode, { name: string; description: string }> = {
  [ModuleCode.Dashboard]: { name: 'Dashboard', description: 'Dashboard and analytics' },
  [ModuleCode.Vendor]: { name: 'Vendors', description: 'Vendor management' },
  [ModuleCode.Material]: { name: 'Materials', description: 'Material management' },
  [ModuleCode.PurchaseOrder]: {
    name: 'Purchase Orders',
    description: 'Purchase order management',
  },
  [ModuleCode.GRN]: { name: 'GRN', description: 'Goods Receipt Note management' },
  [ModuleCode.GRNFieldConfig]: {
    name: 'GRN Field Config',
    description: 'GRN field configuration management',
  },
  [ModuleCode.QC]: { name: 'Quality Control', description: 'Quality control management' },
  [ModuleCode.GatePass]: { name: 'Gate Pass', description: 'Gate pass management' },
  [ModuleCode.Report]: { name: 'Reports', description: 'Reports and analytics' },
  [ModuleCode.User]: { name: 'Users', description: 'User management' },
  [ModuleCode.Role]: { name: 'Roles', description: 'Role management' },
  [ModuleCode.Setting]: { name: 'Settings', description: 'System settings' },
  [ModuleCode.Tenant]: { name: 'Tenants', description: 'Tenant management' },
  [ModuleCode.Plan]: { name: 'Plans', description: 'Plan management' },
  [ModuleCode.Subscription]: { name: 'Subscriptions', description: 'Subscription management' },
  [ModuleCode.Upload]: { name: 'Uploads', description: 'File upload management' },
  [ModuleCode.SuperAdmin]: { name: 'Super Admin', description: 'Super admin management' },
  [ModuleCode.Notification]: { name: 'Notifications', description: 'Notification management' },
  [ModuleCode.ExternalDbConfig]: {
    name: 'External DB Config',
    description: 'External database configuration management',
  },
  [ModuleCode.RFID]: {
    name: 'RFID',
    description: 'RFID card management and scanning',
  },
};
